# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Documentation and examples
author: SINTEF Energy Research
logo: shop_logo.png
only_build_toc_files: true
exclude_patterns: [doc/*]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force #auto, cache, force, off
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sintef-energy/shop-documentation # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
  # extra_extensions:
  #   - sphinx_design

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  # binderhub_url: "https://binder.sintef.energy"  # The URL for your BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: "https://vlab.sintef.energy"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  # thebe: true
